# Generated by Django 3.2.16 on 2024-05-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_editprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
    ]
